#!/bin/sh 

# Set directory and project name
TARGET="todos"
CAPITALIZED_TARGET="Todos"

# Test to make sure "cordova" is in path
which cordova >/dev/null 2>/dev/null

if [ ! "$?" -eq 0  ]
then
	echo ""
	echo "Error:  \"cordova\" not in search path"
	echo ""
	exit 1
fi

# Verify in proper project directory
if [ ! -d ./${TARGET} ]
then
	echo ""
	echo "Aborting:  Not in proper directory."
	echo "Must be in directory which contains \"${TARGET}\""
	echo ""
	exit 1
fi

if [ ! -d ./web_src ]
then
	echo ""
	echo "Aborting:  Not in proper directory."
	echo "Must be in directory which contains 'web_src'"
	echo ""
	exit 1
fi


echo ""
echo "================================"
echo "ENYO:  Start"


cd web_src
tools/deploy.sh
cd ..


echo "ENYO:  Finish"
echo "================================"
echo "TRANSFER:  Start"


cd ${TARGET}

if [ -d www_previous ]
then
	rm -rf www_previous
fi


mv www www_previous
mkdir www
cp www_previous/config.xml www
cp -R www_previous/res www

cd ..
cp -R web_src/deploy/web_src/*	${TARGET}/www

#
#
#
# mv  ${TARGET}/www/index.html  ${TARGET}/www/main.html
# cp  ${TARGET}/www_previous/index.html ${TARGET}/www


#	Copy over the two libraries
# cp web_src/cordova.js				${TARGET}/www
# cp web_src/PushNotification.js	${TARGET}/www


echo "TRANSFER:  Finish"
echo "================================"
echo "CORDOVA:  Start"


cd ${TARGET}

cordova build android >/dev/null 2>/dev/null
# cordova build >/dev/null 2>/dev/null
if [ "$?" -eq 0 ]
then
	echo "Cordova build successful"
else
	echo "Error: Cordova build not successful"
	exit 1
fi


echo "CORDOVA:  Finish"
echo "================================"
echo ""
echo "End of Script"
echo ""
echo "NOTE: If reached this point in script and"
echo "no error messages are displayed (above)"
echo "It can be considered successful."
echo ""






